-- Create table auth
CREATE TABLE IF NOT EXISTS auth (
    token TEXT NOT NULL,
    user_id UUID DEFAULT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    admin_id UUID DEFAULT NULL REFERENCES admins(id) ON DELETE CASCADE ON UPDATE CASCADE,
    role VARCHAR(10) NOT NULL,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);